version: 2.1 # executorsのみ2.1の機能を使っていますが、それ以外は2.0の機能です
executors:
  default:
    working_directory: ~/hugo
    docker:
      - image: cibuilds/hugo:0.54
  ossutil:
    docker:
      - image: golang
jobs:
  test-job:
    executor:
      name: default
    steps:
      - run:
          name: Update enviroment
          command: apk update && apk add git
      - run:
          name: Hugo version
          command: echo "$(hugo version)"
      - checkout
      - run:
          name: Sleep a little
          command: sleep 5
      - run:
          name: Building blog pages
          command: hugo
      - run:
          name: Chat Notification Fail
          when: on_fail
          command: >
            curl --header "Content-Type: application/json"
            --request POST
            --data
            "{
                \"msgtype\": \"link\",
                \"link\": {
                    \"text\": \"SBC Technical Reference auto build failed. Click me for further information\",
                    \"title\": \"Oops. Build ${CIRCLE_BUILD_NUM} failed.\",
                    \"picUrl\": \"https://png.pngtree.com/svg/20170406/icon_failed__1325447.png\",
                    \"messageUrl\": \"${CIRCLE_BUILD_URL}\"
                }
            }"
            $DINGTALK_WEBHOOK_URL

      - run:
          name: Chat Notification Success
          when: on_success
          command: >
            curl --header "Content-Type: application/json"
            --request POST
            --data
            "{
                \"msgtype\": \"link\",
                \"link\": {
                    \"text\": \"SBC Technical Reference auto built successfully. Click me for further information\",
                    \"title\": \"Build ${CIRCLE_BUILD_NUM} passed.\",
                    \"picUrl\": \"https://png.pngtree.com/svg/20170510/success_404253.png\",
                    \"messageUrl\": \"${CIRCLE_BUILD_URL}\"
                }
            }"
            $DINGTALK_WEBHOOK_URL
  deploy-job:
    executor:
      name: default
    steps:
      - run:
          name: Update enviroment
          command: apk update && apk add git
      - run:
          name: Hugo version
          command: echo "$(hugo version)"
      - checkout
      - run:
          name: Sleep a little
          command: sleep 5
      - run:
          name: Build Hugo contents
          command: |
            hugo
      - run:
          name: Sleep a little
          command: sleep 5
      - run:
          name: Deploy to GitHub Pages
          command: |
            chmod +x ./.circleci/deploy.sh
            sh -x ./.circleci/deploy.sh
      - run:
          name: Chat Notification Fail
          when: on_fail
          command: >
            curl --header "Content-Type: application/json"
            --request POST
            --data
            "{
                \"msgtype\": \"link\",
                \"link\": {
                    \"text\": \"SBC Technical Reference deploy to production failed.
                     Click me for further information\",
                    \"title\": \"Oops. Build ${CIRCLE_BUILD_NUM} failed and NOT deployed to production.\",
                    \"picUrl\": \"https://png.pngtree.com/svg/20170406/icon_failed__1325447.png\",
                    \"messageUrl\": \"${CIRCLE_BUILD_URL}\"
                }
            }"
            $DINGTALK_WEBHOOK_URL

      - run:
          name: Chat Notification Success
          when: on_success
          command: >
            curl --header "Content-Type: application/json"
            --request POST
            --data
            "{
                \"msgtype\": \"link\",
                \"link\": {
                    \"text\": \"SBC Technical Reference successfully deployed to production.
                     Click me for further information\",
                    \"title\": \"Build ${CIRCLE_BUILD_NUM} passed and DEPLOYED to PRODUCTION.\",
                    \"picUrl\": \"https://png.pngtree.com/svg/20170510/success_404253.png\",
                    \"messageUrl\": \"${CIRCLE_BUILD_URL}\"
                }
            }"
            $DINGTALK_WEBHOOK_URL
  oss-deploy-job:
    executor:
      name: ossutil
    steps:
      - run:
          name: Update enviroment
          command: apt-get update && apt-get install -y git hugo
      - run:
          name: Install OSS util tool
          command: go get github.com/aliyun/ossutil && ossutil --version
      - checkout
      - run:
          name: Sleep a little
          command: sleep 5
      - run:
          name: Build Hugo contents
          command: |
            hugo
      - run:
          name: OSS util config
          command: |
            cat > ~/.ossutilconfig \<\< "EOF"
            [Credentials]
            language=EN
            endpoint=oss-ap-northeast-1.aliyuncs.com
            accessKeyID=$OSS_ACCESS_KEY_ID
            accessKeySecret=$OSS_ACCESS_KEY_SECRET
            EOF
      - run:
          name: Deploy to OSS Pages
          command: |
            chmod +x ./.circleci/oss-deploy.sh
            sh -x ./.circleci/oss-deploy.sh
      - run:
          name: Chat Notification Fail
          when: on_fail
          command: >
            curl --header "Content-Type: application/json"
            --request POST
            --data
            "{
                \"msgtype\": \"link\",
                \"link\": {
                    \"text\": \"SBC Technical Reference deploy to production failed.
                     Click me for further information\",
                    \"title\": \"Oops. Build ${CIRCLE_BUILD_NUM} failed and NOT deployed to production.\",
                    \"picUrl\": \"https://png.pngtree.com/svg/20170406/icon_failed__1325447.png\",
                    \"messageUrl\": \"${CIRCLE_BUILD_URL}\"
                }
            }"
            $DINGTALK_WEBHOOK_URL

      - run:
          name: Chat Notification Success
          when: on_success
          command: >
            curl --header "Content-Type: application/json"
            --request POST
            --data
            "{
                \"msgtype\": \"link\",
                \"link\": {
                    \"text\": \"SBC Technical Reference successfully deployed to production.
                     Click me for further information\",
                    \"title\": \"Build ${CIRCLE_BUILD_NUM} passed and DEPLOYED to PRODUCTION.\",
                    \"picUrl\": \"https://png.pngtree.com/svg/20170510/success_404253.png\",
                    \"messageUrl\": \"${CIRCLE_BUILD_URL}\"
                }
            }"
            $DINGTALK_WEBHOOK_URL

workflows:
  test-and-deploy:
    jobs:
      - test-job
      - deploy-job:
          requires:
            - test-job
          filters:
            branches:
              only:
                - master
      - oss-deploy-job:
          filters:
            branches:
              only:
                - oss-prod-deploy
