version: 2.1 # executorsのみ2.1の機能を使っていますが、それ以外は2.0の機能です
executors:
  default:
    working_directory: ~/hugo
    docker:
      - image: cibuilds/hugo:latest
jobs:
  test-job:
    executor:
      name: default
    steps:
      - run:
          name: Update enviroment
          command: apk update && apk add git
      - run:
          name: Hugo version
          command: echo "$(hugo version)"
      - checkout
      - run:
          name: Building blog pages
          command: |
            HUGO_ENV=production hugo -v
            hugo
      - run:
          name: Chat Notification Fail
          when: on_fail
          command: >
            curl --header "Content-Type: application/json"
            --request POST
            --data
            "{
                \"msgtype\": \"link\",
                \"link\": {
                    \"text\": \"${CIRCLE_TAG} ${CIRCLE_PROJECT_REPONAME}\",
                    \"title\": \"Oops. Build ${CIRCLE_BUILD_NUM} failed.\",
                    \"picUrl\": \"https://png.pngtree.com/svg/20170406/icon_failed__1325447.png\",
                    \"messageUrl\": \"${CIRCLE_BUILD_URL}\"
                }
            }"
            $DINGTALK_WEBHOOK_URL


      - run:
          name: Chat Notification Success
          when: on_success
          command: >
            curl --header "Content-Type: application/json"
            --request POST
            --data
            "{
                \"msgtype\": \"link\",
                \"link\": {
                    \"text\": \"${CIRCLE_TAG} ${CIRCLE_PROJECT_REPONAME}\",
                    \"title\": \"Build ${CIRCLE_BUILD_NUM} passed.\",
                    \"picUrl\": \"https://png.pngtree.com/svg/20170510/success_404253.png\",
                    \"messageUrl\": \"${CIRCLE_BUILD_URL}\"
                }
            }"
            $DINGTALK_WEBHOOK_URL
  deploy-job:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Deploy to GitHub Pages
          command: |
            chmod +x ./.circleci/deploy.sh
            sh ./.circleci/deploy.sh

workflows:
  test-and-deploy:
    jobs:
      - test-job
      - deploy-job:
          requires:
            - test-job
          filters:
            branches:
              only:
                - master
